# promtail/promtail-config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container
      - source_labels: ["__meta_docker_container_label_app"]
        target_label: app
      - source_labels: ["__meta_docker_container_label_logging"]
        regex: promtail
        action: keep

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\s+\[(?P<thread>[^\]]+)\]\s+(?P<level>\w+)\s+(?P<logger>\S+)\s+-\s+(?P<message>.+)$'

      - labels:
          level:
          logger:
          thread:

      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
      - match:
          selector: '{level="ERROR"}'
          stages:
            - labels:
                severity: error

      - match:
          selector: '{level="WARN"}'
          stages:
            - labels:
                severity: warning

      - match:
          selector: '{level=~"INFO|DEBUG"}'
          stages:
            - labels:
                severity: info